In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("js.csv")
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

## Data Preprocessing

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  object
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  object
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  object
 5   company_size      250000 non-null  object
 6   location          250000 non-null  object
 7   remote_work       250000 non-null  object
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 19.1+ MB

In [4]:
df.isnull().sum()

job_title           0
experience_years    0
education_level     0
skills_count        0
industry            0
company_size        0
location            0
remote_work         0
certifications      0
salary              0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

Here there is no need of any data preprocessing. Now we move to our goal.

## Feature Engineering

In [6]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069

1.we start with experince_years: From experience_years we made another column Experience_level

In [7]:
df["experience_years"].unique()

array([10,  5, 18, 19, 15,  0,  6,  4,  1,  8,  3, 14, 11,  9, 17, 12, 13,
        2,  7, 20, 16])

In [8]:
def experience_level(x):
    if x <= 2:
        return "Junior"
    elif x<= 5:
        return "Mid"
    else:
        return "Senior"
df["Experience_Level"] = df["experience_years"].apply(experience_level)

In [9]:
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,Experience_Level
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,Senior
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,Mid
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123,Senior
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123,Senior
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,Senior

2. From education level we made education status

In [10]:
df["education_level"].unique()

array(['Bachelor', 'PhD', 'High School', 'Diploma', 'Master'],
      dtype=object)

In [11]:
def education(x):
    if x == "High School" or x == "Diploma":
        return "Basic education"
    else:
        return "Higher Education"
df["Education_status"] = df["education_level"].apply(education)
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,Experience_Level,Education_status
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,Senior,Higher Education
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,Mid,Higher Education
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123,Senior,Higher Education
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123,Senior,Higher Education
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,Senior,Higher Education

3.From skill_counts we made another column Skills level

In [12]:
df["skills_count"].unique()

array([ 2, 17,  4, 13,  7, 16, 18, 14, 10,  3,  5,  9,  1, 12, 15,  8, 19,
       11,  6])

In [13]:
def skills_level(x):
    if x <= 5:
        return "Low"
    elif x <= 10:
        return "Medium"
    else:
        return "High"
df["Skills_level"] = df["skills_count"].apply(skills_level)
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,Experience_Level,Education_status,Skills_level
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,Senior,Higher Education,Low
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,Mid,Higher Education,High
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123,Senior,Higher Education,Low
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123,Senior,Higher Education,High
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,Senior,Higher Education,Medium

4. from skills counts and experience_level we made another column Skills_per_year

In [14]:
df["Skills_per_year"] = df["skills_count"]/ (df["experience_years"] + 1)
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,Experience_Level,Education_status,Skills_level,Skills_per_year
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,Senior,Higher Education,Low,0.181818
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,Mid,Higher Education,High,2.833333
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123,Senior,Higher Education,Low,0.210526
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123,Senior,Higher Education,High,0.650000
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,Senior,Higher Education,Medium,0.437500

In [15]:
df["certifications"].unique()

array([2, 0, 1, 3, 5, 4])

In [16]:
df["location"].unique()

array(['India', 'Australia', 'Singapore', 'Canada', 'Sweden', 'USA',
       'Netherlands', 'Remote', 'Germany', 'UK'], dtype=object)

5. Now creates a new feature called Salary based on skill and experience, which measures how much salary a person earns relative to their skills and experience.

In [17]:
df["salary based on skills&exp"]  = df["salary"] / (df["skills_count"] * (df["experience_years"] + 1))
df.head()

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary,Experience_Level,Education_status,Skills_level,Skills_per_year,salary based on skills&exp
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413,Senior,Higher Education,Low,0.181818,4973.318182
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764,Mid,Higher Education,High,2.833333,919.254902
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123,Senior,Higher Education,Low,0.210526,1948.986842
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123,Senior,Higher Education,High,0.650000,727.396154
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069,Senior,Higher Education,Medium,0.437500,1473.830357

## This is just a trailer we made more and more new columns from these data sets